from enum import Enum


class Status(str, Enum):
    FEASIBLE = "FEASIBLE"
    INFEASIBLE = "INFEASIBLE"
    ERROR = "ERROR"


class ReasonCode(str, Enum):
    OK = "OK"
    TARGET_ALREADY_SATISFIED = "TARGET_ALREADY_SATISFIED"
    NO_MUTABLE_FEATURE = "NO_MUTABLE_FEATURE"
    TARGET_UNREACHABLE_UNDER_CONSTRAINTS = "TARGET_UNREACHABLE_UNDER_CONSTRAINTS"
    MEDICAL_RULE_VIOLATION_ONLY = "MEDICAL_RULE_VIOLATION_ONLY"
    TIMEOUT_NO_FEASIBLE_SOLUTION = "TIMEOUT_NO_FEASIBLE_SOLUTION"
    INVALID_INPUT_SCHEMA = "INVALID_INPUT_SCHEMA"
    ENGINE_NOT_READY = "ENGINE_NOT_READY"
    INTERNAL_ERROR = "INTERNAL_ERROR"
